site_name: "Khanh N. Dang"

markdown_extensions:
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist
  - pymdownx.tabbed
  - meta
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.pathconverter
  - pymdownx.tabbed
  - pymdownx.tasklist
  - tables
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.superfences
  - abbr
  - attr_list
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 
theme: 
  name: material
  # logo: assets/logo_2025.svg
  favicon: assets/favicon.png
  custom_dir: overrides   
  logo_dark_mode: assets/logo_2025_dark.svg
  logo_light_mode: assets/logo_2025_light.svg
  # font: false
  font:
    text: "Noto Sans JP"
    code: "Noto Sans Mono"
  icon:
    annotation: material/arrow-right-circle
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.sections
    - toc.follow
    # - toc.integrate
    - navigation.top
    - navigation.indexes
    - navigation.path
    - header.autohide
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: white
      accent: orange
      scheme: default 
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      accent: orange
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to dark mode



nav: 
  - 'Home': index.md
  - 'Research': 
    - 'Research Topic': research.md
    - 'Project': project.md
    - 'Patent': patent.md
    - 'Grant & Award': grant.md
    - 'Open HW/SW': open.md

  - 'Publication': pub.md
  - 'Teaching': teaching.md
  - 'Service': service.md
  - 'Resource': resource.md
  - 'Group member': grp_mem.md
  - '📌 Join Us': 
      - 'How to join': joinus.md
      - 'For undergraduate students': joinus_under.md
      - 'For postgraduate candidates': joinus_post.md
      - 'Scholarship': scholarship.md
      - 'TA/RA/Part-time': tara.md
      - 'How to write research plan': researchplan.md
      - 'How we work': howwework.md
      - 'What you learn': whatyoulearn.md
      - 'Case Study': mentor.md
  - '🖼️ Moment':
    - moment/index.md
  - 'Lab Website': https://web-ext.u-aizu.ac.jp/misc/neuro-eng/
  - 'Contact': contact.md

plugins:
  - search
  - glightbox
  - encryptcontent: 
        title_prefix: ''
        summary: '㊙️ This page is encrypted. '
  - blog:
      blog_dir: moment
      authors: false
      blog_toc: false
      archive_name: Archive      
      archive_date_format: MMMM yyyy
      archive_url_date_format: yyyy/MM
      archive_url_format: "archive/{date}"
      archive_toc: false
      categories_toc: false
      categories_name: Categories
      categories_allowed:
        - Conference
        - Graduation
        - Journal
        - Travel
        - News
        - Interview
      pagination_per_page: 5
      # archive_pagination_per_page: 10
      categories_pagination_per_page: 10
  - tags:
      tags_file: moment/tags.md

extra:
  generator: false
  # social:
  #   - icon: fontawesome/brands/github 
  #     link: https://github.com/klab-aizu
  #   - icon: fontawesome/brands/slack
  #     link: https://klab-aizu.slack.com/
  analytics:
    provider: google
    property: G-N80STK0V0X

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css
copyright: Copyright &copy; 2016 -  Khanh N. Dang. 🌱 This website supports dark mode to <a href="https://doi.org/10.1145/3458864.3467682">save power on OLED or AMOLED displays</a>, aligning with our commitment to sustainability and carbon neutrality.  

