site_name: "Khanh N. Dang"

markdown_extensions:
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist
  - pymdownx.tabbed
  - meta
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.pathconverter
  - pymdownx.tabbed
  - pymdownx.tasklist
  - tables
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.superfences
  - abbr
  - attr_list
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 
theme: 
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.png
  # font: false
  font:
    # text: "Noto Sans Japanese"
    text: "Zen Maru Gothic"
    code: "Noto Sans Mono"
  icon:
    annotation: material/arrow-right-circle
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.sections
    - toc.follow
    # - toc.integrate
    - navigation.top
    - navigation.indexes
    - navigation.path
    - header.autohide
  palette:

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      accent: orange
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: white
      accent: orange
      scheme: default 
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

nav: 
  - 'Home': index.md
  - 'Research': research.md
  - 'Patent': patent.md
  - 'Publication': pub.md
  - 'Teaching': teaching.md
  - 'Group member': grp_mem.md
  - 'Mentoring': mentor.md
  - 'Service': service.md
  - 'Open-source': open.md
  - 'Resource': resource.md
  - 'Lab Website': https://web-ext.u-aizu.ac.jp/misc/neuro-eng/
  - 'Contact': contact.md

plugins:
  - search
  # - glightbox
  - encryptcontent: 
        title_prefix: ''
        summary: '㊙️ This page is encrypted. '
        
extra:
  generator: false
  # social:
  #   - icon: fontawesome/brands/github 
  #     link: https://github.com/klab-aizu
  #   - icon: fontawesome/brands/slack
  #     link: https://klab-aizu.slack.com/
  analytics:
    provider: google
    property: G-N80STK0V0X

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css
copyright: Copyright &copy; 2016 -  Khanh N. Dang. All rights are reserved unless under certain specific statements. 
