site_name: "Khanh N. Dang"

index_page: [index.md]
markdown_extensions:
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist
  - pymdownx.tabbed
  - meta
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.pathconverter
  - pymdownx.tabbed
  - pymdownx.tasklist
  - tables
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 
theme: 
  name: material
  logo: assets/logo.svg
  font: false
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    # - navigation.sections
    - toc.follow
    # - navigation.top
    - navigation.indexes
    - navigation.path

  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: white
      accent: orange
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: white
      accent: orange
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      accent: orange
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
nav: 
  - 'Home': index.md
  - 'Research': research.md
  - 'Publication': pub.md
  - 'Teaching': education.md
  - 'Group': grp_mem.md
  - 'Mentoring': mentor.md
  - 'Contact': contact.md

plugins:
  - search
  - encryptcontent: 
        title_prefix: ''
        summary: '㊙️ This page is encrypted. '
        
extra:
  generator: false
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css
copyright: Copyright &copy; 2016 -  Khanh N. Dang. All rights are reserved unless under certain specific statements. The website is built using mkdocs and updated using cron.
